"""empty message

Revision ID: 414a940d128c
Revises: 
Create Date: 2019-02-23 17:35:05.918174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414a940d128c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alamat', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'alamat')
    # ### end Alembic commands ###
